-- INSERT DATA INTO UMPIRE TABLE WITH NO_OF_MATCH_CONDUCTED SET TO 0
INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70100, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70101, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70102, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70103, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70104, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70105, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70106, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70107, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70108, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (70109, 0);
