-- INSERTING INTERNATIONAL CRICKET VENUES INTO THE VENUE TABLE
INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (1, 'LORD''S CRICKET GROUND', 30000, 'LONDON, ENGLAND');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (2, 'MELBOURNE CRICKET GROUND', 100024, 'MELBOURNE, AUSTRALIA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (3, 'EDEN GARDENS', 66000, 'KOLKATA, INDIA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (4, 'NEWLANDS CRICKET GROUND', 25000, 'CAPE TOWN, SOUTH AFRICA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (5, 'LAHORE GADDAFI STADIUM', 27000, 'LAHORE, PAKISTAN');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES (6, 'SYDNEY CRICKET GROUND', 48000, 'SYDNEY, AUSTRALIA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES   (7, 'WANKHEDE STADIUM', 33000, 'MUMBAI, INDIA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES   (8, 'DUBAI INTERNATIONAL CRICKET STADIUM', 25000, 'DUBAI, UAE');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES   (9, 'SUPERSPORT PARK', 22000, 'CENTURION, SOUTH AFRICA');

INSERT INTO VENUE (VENUE_ID, VENUE_NAME, CAPACITY, LOCATION)
VALUES   (10, 'KENSINGTON OVAL', 28000, 'BRIDGETOWN, BARBADOS');