--DONE
CREATE TABLE PERSON (
    PERSONID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(255),
    LAST_NAME VARCHAR2(255),
    NATIONALITY VARCHAR2(100),
    DATE_OF_BIRTH DATE,
    IMAGE BLOB
);

--DONE
CREATE TABLE UMPIRE (
    PERSONID NUMBER PRIMARY KEY,
    NO_OF_MATCH_CONDUCTED NUMBER,
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID)
);

--DONE
CREATE TABLE TEAM (
    TEAM_ID NUMBER PRIMARY KEY,
    TEAM_NAME VARCHAR2(255),
    CAPTAIN_NAME VARCHAR2(255),
    COACH_NAME VARCHAR2(255)
);

CREATE TABLE STATS (
    STATID NUMBER PRIMARY KEY,
);

CREATE TABLE PLAYER (
    PLAYERID NUMBER PRIMARY KEY,
    TYPE VARCHAR2(50),
    TEAM_ID NUMBER,
    STATID NUMBER UNIQUE,
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY (STATID) REFERENCES STATS(STATID)
);

CREATE TABLE BOWLER (
    PLAYERID NUMBER PRIMARY KEY,
    BOWLING_STYLE VARCHAR2(50),
    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)
);

CREATE TABLE BATSMAN (
    PLAYERID NUMBER PRIMARY KEY,
    BATTING_STYLE VARCHAR2(50),
    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)
);

--DONE
CREATE TABLE COACH (
    PERSONID NUMBER PRIMARY KEY,
    START_DATE_OF_CAREER DATE,
    TEAM_ID NUMBER,
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE PLAYER_STATS (
    STATID NUMBER PRIMARY KEY,
    TOTALMOTM NUMBER,
    TOTALFAIRPLAYAWARD NUMBER,
    FOREIGN KEY (STATID) REFERENCES STATS(STATID)
);

CREATE TABLE TEAM_STATS (
    STATID NUMBER PRIMARY KEY,
    TEAM_ID NUMBER,
    NOOFWINS NUMBER,
    NOOFLOSSES NUMBER,
    NOOFDRAWS NUMBER,
    MATCHABANDONED NUMBER,
    MATCHNOTPLAYED NUMBER,
    POINTSSOFAR NUMBER,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY (STATID) REFERENCES STATS(STATID) 
);

CREATE TABLE FIELDING_STAT (
    STATID NUMBER PRIMARY KEY,
    PLAYERID NUMBER,
    TOTAL_CATCH NUMBER,
    RUN_OUT NUMBER,
    TEAM_ID NUMBER,
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
    FOREIGN KEY(PLAYERID) REFERENCES PLAYER(PLAYERID)

);

CREATE TABLE BATTING_STAT (
    STATID NUMBER PRIMARY KEY,
    PLAYERID NUMBER 
    HUNDREDS NUMBER,
    FIFTIES NUMBER,
    TOTAL_RUN NUMBER,
    NOT_OUT NUMBER,
    AVG NUMBER,
    STR_RATE NUMBER,
    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
    FOREIGN KEY(PLAYERID) REFERENCES PLAYER(PLAYERID)

);

CREATE TABLE BOWLING_STAT (
    STATID NUMBER PRIMARY KEY,
    PLAYERID NUMBER,
    WICKETS NUMBER,
    FIVE_WICKETS NUMBER,
    NO_OF_OVERS NUMBER,
    BOWLING_AVG NUMBER,
    BOWLING_STRIKE_RATE NUMBER,
    NO_OF_HATRICKS NUMBER,
    PLAYERID NUMBER 
    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID);

);

--DONE
CREATE TABLE VENUE (
    VENUE_ID NUMBER PRIMARY KEY,
    VENUE_NAME VARCHAR2(255),
    CAPACITY NUMBER,
    LOCATION VARCHAR2(255)
);

--DONE
CREATE TABLE TOURNAMENT (
    TOURNAMENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR2(255),
    WINNER NUMBER,
    ORGANIZER VARCHAR2(255),
    NO_OF_SIXES NUMBER,
    NO_OF_FOURS NUMBER,
    NO_OF_HAT_TRICKS NUMBER,
    FOREIGN KEY (WINNER) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE TEAM_PARTICIPATES_IN_SERIES (
    TEAM_ID NUMBER,
    SERIES_ID NUMBER,
    PRIMARY KEY (TEAM_ID,
SERIES_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(SERIES_ID)
);

CREATE TABLE MATCH (
    MATCH_ID NUMBER PRIMARY KEY,
    MAN_OF_THE_MATCH NUMBER,
    WEATHER VARCHAR2(50),
    WINNER NUMBER,
    TEAM1_ID NUMBER,
    TEAM2_ID NUMBER,
    VENUE_ID NUMBER,
    SERIES_ID NUMBER,
-- OTHER ATTRIBUTES RELATED TO MATCHES
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(SERIES_ID),
    FOREIGN KEY (WINNER) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE MATCH_UMPIRE (
    MATCH_ID NUMBER,
    UMPIRE_ID NUMBER,
    PRIMARY KEY (MATCH_ID,
UMPIRE_ID),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
    FOREIGN KEY (UMPIRE_ID) REFERENCES UMPIRE(PERSONID)
);

CREATE TABLE PLAYS (
    MATCH_ID NUMBER,
    TEAM_ID NUMBER,
    SCHEDULE DATE,
    PRIMARY KEY (MATCH_ID,
TEAM_ID),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE SCORECARD (
    SCORECARD_ID NUMBER PRIMARY KEY,
    PLAYER_ID NUMBER,
    MATCH_ID NUMBER , 
    OVERS_BOWLED NUMBER,
    TAKEN_WICKETS NUMBER,
    GIVEN_TOTAL_RUNS NUMBER,
    TOTAL_RUNS NUMBER,
    TOTAL_BALLS_FACED NUMBER,
    GIVEN_EXTRAS NUMBER,
    MAIDEN_OVERS_GIVEN NUMBER,
    TOTAL_SIXES_HIT NUMBER,
    TOTAL_FOURS_HIT NUMBER,
    DEMERIT_POINTS NUMBER,
    PENALIZED NUMBER,
    TOTAL_CATCHES_TAKEN NUMBER,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID)
);
