CREATE OR REPLACE PROCEDURE INSERT_SELECTED_PLAYERS_TO_DREAM11(SELECTED_PLAYERS INTEGER[])
LANGUAGE plpgsql
AS $$
DECLARE
    CUR_PLAYER_ID INTEGER;
    CUR_TEAM_ID INTEGER;
BEGIN
    FOREACH CUR_PLAYER_ID IN ARRAY SELECTED_PLAYERS
    LOOP
        SELECT TEAM_ID INTO CUR_TEAM_ID FROM PLAYER WHERE PLAYERID = CUR_PLAYER_ID;
        INSERT INTO DREAM11(PLAYERID, TEAM_ID) VALUES (CUR_PLAYER_ID, CUR_TEAM_ID);
    END LOOP;
END;
$$;


CREATE OR REPLACE PROCEDURE CALCULATE_DREAM11_POINTS(OUT TOTAL_POINTS INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
    CUR_PLAYERID RECORD;
    PLAYER_POINTS INTEGER;
BEGIN
    -- Initialize total points for the team
    TOTAL_POINTS := 0;
    
    -- Iterate through each player in the DREAM11 team
    FOR CUR_PLAYERID IN (SELECT PLAYERID FROM DREAM11) LOOP
        -- Call the DREAM11_PLAYERS_POINT function to calculate points for each player
        PLAYER_POINTS := DREAM11_PLAYERS_POINT(CUR_PLAYERID.PLAYERID);
        -- Add player points to the total points
        TOTAL_POINTS := TOTAL_POINTS + PLAYER_POINTS;
    END LOOP;
END;
$$;


