CREATE OR REPLACE TRIGGER DELETE_TOURNAMENT_TRIGGER
BEFORE DELETE ON TOURNAMENT
FOR EACH ROW
EXECUTE FUNCTION DELETE_TOURNAMENT();


CREATE OR REPLACE TRIGGER UPDATE_UMPIRE_MATCHES_TRIGGER
AFTER INSERT ON MATCH_UMPIRE
FOR EACH ROW
EXECUTE FUNCTION UPDATE_UMPIRE_MATCHES();


CREATE OR REPLACE TRIGGER CASCADE_DELETE_SCORECARDS
AFTER DELETE ON MATCH
FOR EACH ROW
EXECUTE FUNCTION DELETE_RELATED_SCORECARDS();


CREATE OR REPLACE TRIGGER DELETE_TEAM_TRIGGER
BEFORE DELETE ON TEAM
FOR EACH ROW
EXECUTE FUNCTION DELETE_TEAM();


CREATE OR REPLACE TRIGGER DELETE_PERSON_TRIGGER
BEFORE DELETE ON PERSON
FOR EACH ROW
EXECUTE FUNCTION DELETE_PERSON();
