-- ADD CASCADING DELETE CONSTRAINT TO THE POINT_TABLE TABLE
ALTER TABLE POINT_TABLE
ADD CONSTRAINT FK_TOURNAMENT_ID
FOREIGN KEY (TOURNAMENT_ID)
REFERENCES TOURNAMENT(TOURNAMENT_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE TEAM_PARTICIPATION TABLE
ALTER TABLE TEAM_PARTICIPATION
ADD CONSTRAINT FK_TOURNAMENT_ID
FOREIGN KEY (TOURNAMENT_ID)
REFERENCES TOURNAMENT(TOURNAMENT_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE MATCH TABLE
ALTER TABLE MATCH
ADD CONSTRAINT FK_TOURNAMENT_ID
FOREIGN KEY (TOURNAMENT_ID)
REFERENCES TOURNAMENT(TOURNAMENT_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE SCORECARD TABLE
ALTER TABLE SCORECARD
ADD CONSTRAINT FK_MATCH_ID
FOREIGN KEY (MATCH_ID)
REFERENCES MATCH(MATCH_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE AWARD TABLE
ALTER TABLE AWARD
ADD CONSTRAINT FK_TOURNAMENT_ID
FOREIGN KEY (TOURNAMENT_ID)
REFERENCES TOURNAMENT(TOURNAMENT_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE MATCH_UMPIRE TABLE
ALTER TABLE MATCH_UMPIRE
ADD CONSTRAINT FK_MATCH_ID
FOREIGN KEY (MATCH_ID)
REFERENCES MATCH(MATCH_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE TEAM_HEAD_TO_HEAD TABLE FOR BOTH TEAM1_ID AND TEAM2_ID
ALTER TABLE TEAM_HEAD_TO_HEAD
ADD CONSTRAINT FK_TEAM1_ID
FOREIGN KEY (TEAM1_ID)
REFERENCES TEAM(TEAM_ID)
ON DELETE CASCADE;

ALTER TABLE TEAM_HEAD_TO_HEAD
ADD CONSTRAINT FK_TEAM2_ID
FOREIGN KEY (TEAM2_ID)
REFERENCES TEAM(TEAM_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE PLAYER_PERFORMANCE TABLE
ALTER TABLE PLAYER_PERFORMANCE
ADD CONSTRAINT FK_MATCH_ID
FOREIGN KEY (MATCH_ID)
REFERENCES MATCH(MATCH_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE DREAM11 TABLE
ALTER TABLE DREAM11
ADD CONSTRAINT FK_TEAM_ID
FOREIGN KEY (TEAM_ID)
REFERENCES TEAM(TEAM_ID)
ON DELETE CASCADE;

-- ADD CASCADING DELETE CONSTRAINT TO THE PLAYER_PROFILE TABLE
ALTER TABLE PLAYER_PROFILE
ADD CONSTRAINT FK_PLAYER_ID
FOREIGN KEY (PLAYERID)
REFERENCES PLAYER(PLAYERID)
ON DELETE CASCADE;
