CREATE TABLE DELETED_TOURNAMENT (
    TOURNAMENT_ID SERIAL PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR(255),
    HOST VARCHAR(255),
    WINNER_TEAM_ID INTEGER,
    NO_OF_SIXES INTEGER,
    NO_OF_FOURS INTEGER,
    NO_OF_HAT_TRICKS INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE DELETED_TOURNAMENT;

CREATE TABLE DELETED_TEAM (
    TEAM_ID SERIAL PRIMARY KEY,
    TEAM_NAME VARCHAR(255),
    COACH_ID VARCHAR(255),
    CAPTAIN_ID VARCHAR(255),
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE DELETED_TEAM;

CREATE TABLE DELETED_PLAYER (
    PLAYERID SERIAL PRIMARY KEY,
    TEAM_ID INTEGER,
    TYPE VARCHAR(255),
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE DELETED_PLAYER;

CREATE TABLE DELETED_PERSON (
    PERSONID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    NATIONALITY VARCHAR(100),
    DATE_OF_BIRTH DATE,
    IMAGE BYTEA,
    DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE DELETED_PERSON;
