CREATE TABLE DELETED_TOURNAMENT (
    TOURNAMENT_ID SERIAL PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR(255),
    HOST VARCHAR(255),
    WINNER_TEAM_ID INTEGER,
    NO_OF_SIXES INTEGER,
    NO_OF_FOURS INTEGER,
    NO_OF_HAT_TRICKS INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    DELETED_AT DATE DEFAULT CURRENT_DATE
);
