--DONE
CREATE TABLE PERSON (
    PERSONID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(255),
    LAST_NAME VARCHAR2(255),
    NATIONALITY VARCHAR2(100),
    DATE_OF_BIRTH DATE,
    IMAGE BLOB
);

--DONE
CREATE TABLE UMPIRE (
    PERSONID NUMBER PRIMARY KEY,
    NO_OF_MATCH_CONDUCTED NUMBER,
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID)
);

--DONE
CREATE TABLE TEAM (
    TEAM_ID NUMBER PRIMARY KEY,
    TEAM_NAME VARCHAR2(255),
    CAPTAIN_ID NUMBER,
    COACH_ID NUMBER
);

--DROP TABLE TEAM;
--DROP TABLE PERSON;
--DROP TABLE UMPIRE;
--DROP TABLE COACH;
--DROP TABLE TOURNAMENT;

--DONE
CREATE TABLE PLAYER (
    PLAYERID NUMBER PRIMARY KEY,
    TEAM_ID NUMBER,
    TYPE VARCHAR2(50),
    FOREIGN KEY (PLAYERID) REFERENCES PERSON(PERSONID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE BOWLER (
    PLAYERID NUMBER PRIMARY KEY,
    BOWLING_STYLE VARCHAR2(50),
    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)
);

--DONE
CREATE TABLE BATSMAN (
    PLAYERID NUMBER PRIMARY KEY,
    BATTING_STYLE VARCHAR2(50),
    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID)
);

--DONE
CREATE TABLE COACH (
    PERSONID NUMBER PRIMARY KEY,
    START_DATE_OF_CAREER DATE,
    TEAM_ID NUMBER,
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--CREATE TABLE FIELDING_STAT (
--    STATID NUMBER PRIMARY KEY,
--    PLAYERID NUMBER,
--    TOTAL_CATCH NUMBER,
--    RUN_OUT NUMBER,
--    TEAM_ID NUMBER,
--    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
--    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
--    FOREIGN KEY(PLAYERID) REFERENCES PLAYER(PLAYERID)
--);
--
--CREATE TABLE BATTING_STAT (
--    STATID NUMBER PRIMARY KEY,
--    PLAYERID NUMBER 
--    HUNDREDS NUMBER,
--    FIFTIES NUMBER,
--    TOTAL_RUN NUMBER,
--    NOT_OUT NUMBER,
--    AVG NUMBER,
--    STR_RATE NUMBER,
--    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
--    FOREIGN KEY(PLAYERID) REFERENCES PLAYER(PLAYERID)
--
--);
--
--CREATE TABLE BOWLING_STAT (
--    STATID NUMBER PRIMARY KEY,
--    PLAYERID NUMBER,
--    WICKETS NUMBER,
--    FIVE_WICKETS NUMBER,
--    NO_OF_OVERS NUMBER,
--    BOWLING_AVG NUMBER,
--    BOWLING_STRIKE_RATE NUMBER,
--    NO_OF_HATRICKS NUMBER,
--    PLAYERID NUMBER 
--    FOREIGN KEY (STATID) REFERENCES PLAYER_STATS(STATID)
--    FOREIGN KEY (PLAYERID) REFERENCES PLAYER(PLAYERID);
--
--);

--DONE
CREATE TABLE VENUE (
    VENUE_ID NUMBER PRIMARY KEY,
    VENUE_NAME VARCHAR2(255),
    CAPACITY NUMBER,
    LOCATION VARCHAR2(255)
);

--DONE
CREATE TABLE TOURNAMENT (
    TOURNAMENT_ID NUMBER PRIMARY KEY,
    TOURNAMENT_NAME VARCHAR2(255),
    HOST VARCHAR2(255),
    WINNER_TEAM_ID NUMBER,
    NO_OF_SIXES NUMBER,
    NO_OF_FOURS NUMBER,
    NO_OF_HAT_TRICKS NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    FOREIGN KEY (WINNER_TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE POINT_TABLE (
	TEAM_ID NUMBER,
	TOURNAMENT_ID NUMBER,
	MATCHES NUMBER,
	WON NUMBER,
	LOST NUMBER,
	DRAW NUMBER,
	POINTS NUMBER,
	NRR NUMBER,
	PRIMARY KEY (TEAM_ID, TOURNAMENT_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
	FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID)
);

--DONE
CREATE TABLE TEAM_PARTICIPATION (
    TEAM_ID NUMBER,
    TOURNAMENT_ID NUMBER,
    PRIMARY KEY (TEAM_ID, TOURNAMENT_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),l
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT (TOURNAMENT_ID)
);

--DONE
CREATE TABLE MATCH (
    MATCH_ID NUMBER PRIMARY KEY,
    TOURNAMENT_ID NUMBER,
    MAN_OF_THE_MATCH NUMBER,
    WINNER NUMBER,
    TEAM1_ID NUMBER,
    TEAM2_ID NUMBER,
    VENUE_ID NUMBER,
    TEAM1_RUN NUMBER,
    TEAM2_RUN NUMBER,
    TEAM1_WICKET NUMBER,
    TEAM2_WICKET NUMBER,
    MATCH_DATE DATE,
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (WINNER) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE MATCH_UMPIRE (
    MATCH_ID NUMBER,
    UMPIRE_ID NUMBER,
    PRIMARY KEY (MATCH_ID, UMPIRE_ID),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
    FOREIGN KEY (UMPIRE_ID) REFERENCES UMPIRE(PERSONID)
);

--CREATE TABLE PLAYS (
--    MATCH_ID NUMBER,
--    TEAM_ID NUMBER,
--    SCHEDULE DATE,
--    PRIMARY KEY (MATCH_ID, TEAM_ID),
--    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
--    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
--);

--DONE
CREATE TABLE SCORECARD (
    SCORECARD_ID NUMBER PRIMARY KEY,
    PLAYER_ID NUMBER,
    MATCH_ID NUMBER , 
    TEAM_ID NUMBER,
    RUN_SCORED NUMBER,
    RUN_GIVEN NUMBER,
    WICKET_TAKEN NUMBER,
    OVERS_BOWLED NUMBER,
    BALL_PLAYED NUMBER,
    GIVEN_EXTRAS NUMBER,
    MAIDEN_OVERS NUMBER,
    TOTAL_SIXES_HIT NUMBER,
    TOTAL_FOURS_HIT NUMBER,
    BALL_FOR_HALF_CENTURY NUMBER,
    BALL_FOR_CENTURY NUMBER,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYERID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE PLAYER_PERFORMANCE (
    MATCH_ID NUMBER PRIMARY KEY,
    PLAYER_ID NUMBER,
    RUNS_SCORED NUMBER,
    BALLS_PLAYED NUMBER,
    OVERS_BOWLED NUMBER,
    WICKETS_TAKEN NUMBER,
    RUNS_CONCEDED NUMBER,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYERID)
);

--DONE
CREATE TABLE AWARD (
	AWARD_ID NUMBER PRIMARY KEY,
	AWARD_NAME VARCHAR2(255),
	TOURNAMENT_ID NUMBER,
	PLAYER_ID NUMBER,
	FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYERID)
);

--DONE
CREATE TABLE TICKET (
	MATCH_ID NUMBER,
	VENUE_ID NUMBER,
	TOTAL_SOLD NUMBER,
	PRIMARY KEY(MATCH_ID, VENUE_ID),
	FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID),
	FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID)
);

--DONE
CREATE TABLE SPONSER (
	SPONSER_ID NUMBER PRIMARY KEY,
	TEAM_ID NUMBER,
	COMPANY_NAME VARCHAR2(255),
	SPONSER_TYPE VARCHAR2(255),
	FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE JERSEY (
	TEAM_ID NUMBER PRIMARY KEY,
	COLOR VARCHAR2(255),
	IMAGE BLOB,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

--DONE
CREATE TABLE HIGHLIGHT(
	MATCH_ID NUMBER PRIMARY KEY,
	VIDEO_URL VARCHAR2(255),
	FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID)
);

--DONE
CREATE TABLE NEWS (
	NEWS_ID NUMBER PRIMARY KEY,
	MATCH_ID NUMBER,
	NEWS_URL VARCHAR2(500),
	FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID)
);





