INSERT INTO BATSMAN (PLAYERID, BATTING_STYLE)
SELECT  PLAYERID, TYPE
FROM PLAYER
WHERE TYPE = 'BATSMAN';

INSERT INTO BOWLER (PLAYERID, BOWLING_STYLE)
SELECT  PLAYERID, TYPE
FROM PLAYER
WHERE TYPE = 'BOWLER';
