-- BANGLADESH COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (110, TO_DATE('2020-01-01', 'YYYY-MM-DD'), 1);

-- INDIA COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (111, TO_DATE('2019-08-16', 'YYYY-MM-DD'), 2);

-- PAKISTAN COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (112, TO_DATE('2022-03-01', 'YYYY-MM-DD'), 3);

-- AUSTRALIA COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (113, TO_DATE('2018-11-01', 'YYYY-MM-DD'), 4);

-- ENGLAND COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (114, TO_DATE('2019-10-07', 'YYYY-MM-DD'), 5);

-- NEW ZEALAND COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (115, TO_DATE('2018-08-01', 'YYYY-MM-DD'), 6);

-- SOUTH AFRICA COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (116, TO_DATE('2019-12-01', 'YYYY-MM-DD'), 7);

-- AFGHANISTAN COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (117, TO_DATE('2021-02-15', 'YYYY-MM-DD'), 8);

-- WEST INDIES COACH DATA
INSERT INTO COACH (PERSONID, START_DATE_OF_CAREER, TEAM_ID)
VALUES (118, TO_DATE('2019-07-01', 'YYYY-MM-DD'), 9);