INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (1, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/rohit-sharma-breaks-silence-for-first-time-since-cwc23-final');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (2, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/buttler-excited-about-fresh-talent-as-england-aim-to-recover-from-world-cup-disappointment');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (3, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/match-officials-named-for-cricket-world-cup-final');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (4, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/deja-vu-for-south-africa-as-semi-final-post-mortem-begins');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (5, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/from-frustrating-injuries-to-leading-blackcaps-into-semis-williamson-on-testing-journey');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (6, 'https://www.icc-cricket.com/tournaments/cricketworldcup/news/shanto-throws-hat-into-ring-for-permanent-bangladesh-captaincy');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (7, '');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (8, '');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (9, '');
INSERT INTO NEWS (MATCH_ID, NEWS_URL) VALUES (10, '');
DELETE FROM NEWS;