-- BANGLADESH PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71101, 'TAMIM', 'IQBAL', 'BANGLADESH', TO_DATE('1989-03-20', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71102, 'SHAKIB', 'AL HASAN', 'BANGLADESH', TO_DATE('1987-03-24', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71103, 'MUSHFIQUR', 'RAHIM', 'BANGLADESH', TO_DATE('1987-06-09', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71104, 'MAHMUDULLAH', 'RIYAD', 'BANGLADESH', TO_DATE('1986-02-04', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71105, 'MUSTAFIZUR', 'RAHMAN', 'BANGLADESH', TO_DATE('1995-09-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71106, 'TASKIN', 'AHMED', 'BANGLADESH', TO_DATE('1995-04-03', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71107, 'LITON', 'DAS', 'BANGLADESH', TO_DATE('1994-10-13', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71108, 'SOUMYA', 'SARKAR', 'BANGLADESH', TO_DATE('1993-02-25', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71109, 'MEHIDY', 'HASAN', 'BANGLADESH', TO_DATE('1997-10-25', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71110, 'MOSADDEK', 'HOSSAIN', 'BANGLADESH', TO_DATE('1995-12-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (71111, 'RUBEL', 'HOSSAIN', 'BANGLADESH', TO_DATE('1990-01-01', 'YYYY-MM-DD'), NULL);

-- INDIA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72101, 'VIRAT', 'KOHLI', 'INDIA', TO_DATE('1988-11-05', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72102, 'ROHIT', 'SHARMA', 'INDIA', TO_DATE('1987-04-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72103, 'JASPRIT', 'BUMRAH', 'INDIA', TO_DATE('1993-12-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72104, 'HARDIK', 'PANDYA', 'INDIA', TO_DATE('1993-10-11', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72105, 'KL', 'RAHUL', 'INDIA', TO_DATE('1992-04-18', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72106, 'RAVINDRA', 'JADEJA', 'INDIA', TO_DATE('1988-12-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72107, 'RISHABH', 'PANT', 'INDIA', TO_DATE('1997-10-04', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72108, 'SHIKHAR', 'DHAWAN', 'INDIA', TO_DATE('1985-12-05', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72109, 'YUZVENDRA', 'CHAHAL', 'INDIA', TO_DATE('1990-07-23', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72110, 'KULDEEP', 'YADAV', 'INDIA', TO_DATE('1994-12-14', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (72111, 'BHUVNESHWAR', 'KUMAR', 'INDIA', TO_DATE('1990-02-05', 'YYYY-MM-DD'), NULL);

-- PAKISTAN PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73101, 'BABAR', 'AZAM', 'PAKISTAN', TO_DATE('1994-10-15', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73102, 'SHAHEEN', 'AFRIDI', 'PAKISTAN', TO_DATE('2000-04-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73103, 'FAKHAR', 'ZAMAN', 'PAKISTAN', TO_DATE('1990-04-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73104, 'MOHAMMAD', 'RIZWAN', 'PAKISTAN', TO_DATE('1992-06-01', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73105, 'SHADAB', 'KHAN', 'PAKISTAN', TO_DATE('1998-10-04', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73106, 'IMAD', 'WASIM', 'PAKISTAN', TO_DATE('1988-12-18', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73107, 'HARIS', 'SOHAIL', 'PAKISTAN', TO_DATE('1989-01-09', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73108, 'SHOAIB', 'MALIK', 'PAKISTAN', TO_DATE('1982-02-01', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73109, 'WAHAB', 'RIAZ', 'PAKISTAN', TO_DATE('1985-06-28', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73110, 'USMAN', 'QADIR', 'PAKISTAN', TO_DATE('1993-08-05', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73111, 'IMRAN', 'KHAN', 'PAKISTAN', TO_DATE('1988-06-10', 'YYYY-MM-DD'), NULL);

-- AUSTRALIA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74101, 'STEVE', 'SMITH', 'AUSTRALIA', TO_DATE('1989-06-02', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74102, 'DAVID', 'WARNER', 'AUSTRALIA', TO_DATE('1986-10-27', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74103, 'AARON', 'FINCH', 'AUSTRALIA', TO_DATE('1986-11-17', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74104, 'GLENN', 'MAXWELL', 'AUSTRALIA', TO_DATE('1988-10-14', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74105, 'MITCHELL', 'STARC', 'AUSTRALIA', TO_DATE('1990-01-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74106, 'PAT', 'CUMMINS', 'AUSTRALIA', TO_DATE('1993-05-08', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74107, 'ADAM', 'ZAMPA', 'AUSTRALIA', TO_DATE('1992-03-31', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74108, 'ALEX', 'CAREY', 'AUSTRALIA', TO_DATE('1991-08-27', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74109, 'MARCUS', 'STOINIS', 'AUSTRALIA', TO_DATE('1989-08-16', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74110, 'MATTHEW', 'WADE', 'AUSTRALIA', TO_DATE('1987-12-26', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74111, 'JOSH', 'HAZLEWOOD', 'AUSTRALIA', TO_DATE('1991-01-08', 'YYYY-MM-DD'), NULL);

-- ENGLAND PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75101, 'JOE', 'ROOT', 'ENGLAND', TO_DATE('1990-12-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75102, 'EOIN', 'MORGAN', 'ENGLAND', TO_DATE('1986-09-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75103, 'JASON', 'ROY', 'ENGLAND', TO_DATE('1990-07-21', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75104, 'JOS', 'BUTTLER', 'ENGLAND', TO_DATE('1990-09-08', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75105, 'BEN', 'STOKES', 'ENGLAND', TO_DATE('1991-06-04', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75106, 'JOFRA', 'ARCHER', 'ENGLAND', TO_DATE('1995-04-03', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75107, 'MARK', 'WOOD', 'ENGLAND', TO_DATE('1990-01-11', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75108, 'ADIL', 'RASHID', 'ENGLAND', TO_DATE('1988-02-17', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75109, 'CHRIS', 'WOAKES', 'ENGLAND', TO_DATE('1989-03-02', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75110, 'TOM', 'CURRAN', 'ENGLAND', TO_DATE('1995-03-12', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75111, 'MOEEN', 'ALI', 'ENGLAND', TO_DATE('1987-06-18', 'YYYY-MM-DD'), NULL);

-- NEW ZEALAND PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76101, 'KANE', 'WILLIAMSON', 'NEW ZEALAND', TO_DATE('1990-08-08', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76102, 'ROSS', 'TAYLOR', 'NEW ZEALAND', TO_DATE('1984-03-08', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76103, 'MARTIN', 'GUPTILL', 'NEW ZEALAND', TO_DATE('1986-09-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76104, 'TRENT', 'BOULT', 'NEW ZEALAND', TO_DATE('1989-07-22', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76105, 'LOCKIE', 'FERGUSON', 'NEW ZEALAND', TO_DATE('1991-06-13', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76106, 'COLIN', 'DE GRANDHOMME', 'NEW ZEALAND', TO_DATE('1986-07-22', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76107, 'TIM', 'SOUTHEE', 'NEW ZEALAND', TO_DATE('1988-12-11', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76108, 'KYLE', 'JAMIESON', 'NEW ZEALAND', TO_DATE('1994-12-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76109, 'JAMES', 'NEESHAM', 'NEW ZEALAND', TO_DATE('1990-09-17', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76110, 'TOM', 'LATHAM', 'NEW ZEALAND', TO_DATE('1992-04-02', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76111, 'MITCHELL', 'SANTNER', 'NEW ZEALAND', TO_DATE('1992-02-05', 'YYYY-MM-DD'), NULL);

-- SOUTH AFRICA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77101, 'QUINTON', 'DE KOCK', 'SOUTH AFRICA', TO_DATE('1992-12-17', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77102, 'FAF', 'DU PLESSIS', 'SOUTH AFRICA', TO_DATE('1984-07-13', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77103, 'DAVID', 'MILLER', 'SOUTH AFRICA', TO_DATE('1989-06-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77104, 'KAGISO', 'RABADA', 'SOUTH AFRICA', TO_DATE('1995-05-25', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77105, 'ANRICH', 'NORTJE', 'SOUTH AFRICA', TO_DATE('1993-11-16', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77106, 'LUNGI', 'NGIDI', 'SOUTH AFRICA', TO_DATE('1996-03-29', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77107, 'RASSIE', 'VAN DER DUSSEN', 'SOUTH AFRICA', TO_DATE('1989-06-07', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77108, 'ANDILE', 'PHEHLUKWAYO', 'SOUTH AFRICA', TO_DATE('1996-03-03', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77109, 'TEMBA', 'BAVUMA', 'SOUTH AFRICA', TO_DATE('1990-05-17', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77110, 'HEINRICH', 'KLAASEN', 'SOUTH AFRICA', TO_DATE('1991-07-30', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77111, 'AIDEN', 'MARKRAM', 'SOUTH AFRICA', TO_DATE('1994-10-04', 'YYYY-MM-DD'), NULL);

-- AFGHANISTAN PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78101, 'RASHID', 'KHAN', 'AFGHANISTAN', TO_DATE('1998-09-20', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78102, 'MOHAMMAD', 'NABI', 'AFGHANISTAN', TO_DATE('1985-01-01', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78103, 'ASGHAR', 'AFGHAN', 'AFGHANISTAN', TO_DATE('1987-12-22', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78104, 'RAHMANULLAH', 'GURBAZ', 'AFGHANISTAN', TO_DATE('2001-09-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78105, 'HAZRATULLAH', 'ZAZAI', 'AFGHANISTAN', TO_DATE('1998-03-23', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78106, 'NAJIBULLAH', 'ZADRAN', 'AFGHANISTAN', TO_DATE('1993-02-01', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78107, 'MOHAMMAD', 'SHAHZAD', 'AFGHANISTAN', TO_DATE('1987-01-31', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78108, 'GULBADIN', 'NAIB', 'AFGHANISTAN', TO_DATE('1991-03-16', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78109, 'DAWLAT', 'ZADRAN', 'AFGHANISTAN', TO_DATE('1988-03-20', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78110, 'KARIM', 'JANAT', 'AFGHANISTAN', TO_DATE('1998-02-25', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78111, 'QAIS', 'AHMAD', 'AFGHANISTAN', TO_DATE('2000-12-05', 'YYYY-MM-DD'), NULL);

-- WEST INDIES PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79101, 'CHRIS', 'GAYLE', 'WEST INDIES', TO_DATE('1979-09-21', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79102, 'ANDRE', 'RUSSELL', 'WEST INDIES', TO_DATE('1988-04-29', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79103, 'SHAI', 'HOPE', 'WEST INDIES', TO_DATE('1993-11-10', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79104, 'KIERON', 'POLLARD', 'WEST INDIES', TO_DATE('1987-05-12', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79105, 'EVIN', 'LEWIS', 'WEST INDIES', TO_DATE('1991-12-27', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79106, 'NICHOLAS', 'POORAN', 'WEST INDIES', TO_DATE('1995-10-02', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79107, 'SHELDON', 'COTTRELL', 'WEST INDIES', TO_DATE('1989-08-19', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79108, 'HAYDEN', 'WALSH', 'WEST INDIES', TO_DATE('1992-12-23', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79109, 'FABIAN', 'ALLEN', 'WEST INDIES', TO_DATE('1995-05-07', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79110, 'ROSTON', 'CHASE', 'WEST INDIES', TO_DATE('1992-03-22', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79111, 'ALZARRI', 'JOSEPH', 'WEST INDIES', TO_DATE('1996-11-20', 'YYYY-MM-DD'), NULL);

-- UMPIRES
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70100, 'SIMON', 'TAUFEL', 'AUSTRALIA', TO_DATE('1971-01-21', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70101, 'ALEEM', 'DAR', 'PAKISTAN', TO_DATE('1968-06-06', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70102, 'KUMAR', 'DHARMASENA', 'SRI LANKA', TO_DATE('1971-04-24', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70103, 'RICHARD', 'KETTLEBOROUGH', 'ENGLAND', TO_DATE('1973-03-15', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70104, 'BRUCE', 'OXENFORD', 'AUSTRALIA', TO_DATE('1960-03-5', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70105, 'MARAIS', 'ERASMUS', 'SOUTH AFRICA', TO_DATE('1964-02-3', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70106, 'PAUL', 'REIFFEL', 'AUSTRALIA', TO_DATE('1966-01-12', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70107, 'JOEL', 'WILSON', 'WEST INDIES', TO_DATE('1966-03-15', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70108, 'NITIN', 'MENON', 'INDIA', TO_DATE('1974-10-31', 'YYYY-MM-DD'), NULL);

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70109, 'CHRIS', 'GAFFANEY', 'NEW ZEALAND', TO_DATE('1975-02-10', 'YYYY-MM-DD'), NULL);

-- BANGLADESH COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (71001, 'RUSSELL', 'DOMINGO', 'SOUTH AFRICA', TO_DATE('1974-08-30', 'YYYY-MM-DD'), NULL);

-- INDIA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (72001, 'RAVI', 'SHASTRI', 'INDIA', TO_DATE('1962-05-27', 'YYYY-MM-DD'), NULL);

-- PAKISTAN COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73001, 'MATTHEW', 'HAYDEN', 'AUSTRALIA', TO_DATE('1971-10-29', 'YYYY-MM-DD'), NULL);

-- AUSTRALIA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74001, 'JUSTIN', 'LANGER', 'AUSTRALIA', TO_DATE('1970-11-21', 'YYYY-MM-DD'), NULL);

-- ENGLAND COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75001, 'CHRIS', 'SILVERWOOD', 'ENGLAND', TO_DATE('1975-03-05', 'YYYY-MM-DD'), NULL);

-- NEW ZEALAND COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76001, 'GARY', 'STEAD', 'NEW ZEALAND', TO_DATE('1972-08-23', 'YYYY-MM-DD'), NULL);

-- SOUTH AFRICA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77001, 'MARK', 'BOUCHER', 'SOUTH AFRICA', TO_DATE('1976-12-03', 'YYYY-MM-DD'), NULL);

-- AFGHANISTAN COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78001, 'LANCE', 'KLUSENER', 'SOUTH AFRICA', TO_DATE('1971-09-04', 'YYYY-MM-DD'), NULL);

-- WEST INDIES COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79001, 'PHIL', 'SIMMONS', 'WEST INDIES', TO_DATE('1963-04-18', 'YYYY-MM-DD'), NULL);
