-- BANGLADESH PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (1, 'TAMIM', 'IQBAL', 'BANGLADESH', TO_DATE('1989-03-20', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (2, 'SHAKIB', 'AL HASAN', 'BANGLADESH', TO_DATE('1987-03-24', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (3, 'MUSHFIQUR', 'RAHIM', 'BANGLADESH', TO_DATE('1987-06-09', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (4, 'MAHMUDULLAH', 'RIYAD', 'BANGLADESH', TO_DATE('1986-02-04', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (5, 'MUSTAFIZUR', 'RAHMAN', 'BANGLADESH', TO_DATE('1995-09-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (6, 'TASKIN', 'AHMED', 'BANGLADESH', TO_DATE('1995-04-03', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (7, 'LITON', 'DAS', 'BANGLADESH', TO_DATE('1994-10-13', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (8, 'SOUMYA', 'SARKAR', 'BANGLADESH', TO_DATE('1993-02-25', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (9, 'MEHIDY', 'HASAN', 'BANGLADESH', TO_DATE('1997-10-25', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (10, 'MOSADDEK', 'HOSSAIN', 'BANGLADESH', TO_DATE('1995-12-10', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (11, 'RUBEL', 'HOSSAIN', 'BANGLADESH', TO_DATE('1990-01-01', 'YYYY-MM-DD'), EMPTY_BLOB());
-- INDIA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (12, 'VIRAT', 'KOHLI', 'INDIA', TO_DATE('1988-11-05', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (13, 'ROHIT', 'SHARMA', 'INDIA', TO_DATE('1987-04-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (14, 'JASPRIT', 'BUMRAH', 'INDIA', TO_DATE('1993-12-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (15, 'HARDIK', 'PANDYA', 'INDIA', TO_DATE('1993-10-11', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (16, 'KL', 'RAHUL', 'INDIA', TO_DATE('1992-04-18', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (17, 'RAVINDRA', 'JADEJA', 'INDIA', TO_DATE('1988-12-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (18, 'RISHABH', 'PANT', 'INDIA', TO_DATE('1997-10-04', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (19, 'SHIKHAR', 'DHAWAN', 'INDIA', TO_DATE('1985-12-05', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (20, 'YUZVENDRA', 'CHAHAL', 'INDIA', TO_DATE('1990-07-23', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (21, 'KULDEEP', 'YADAV', 'INDIA', TO_DATE('1994-12-14', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE) VALUES
    (22, 'BHUVNESHWAR', 'KUMAR', 'INDIA', TO_DATE('1990-02-05', 'YYYY-MM-DD'), EMPTY_BLOB());
-- PAKISTAN PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (23, 'BABAR', 'AZAM', 'PAKISTAN', TO_DATE('1994-10-15', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (24, 'SHAHEEN', 'AFRIDI', 'PAKISTAN', TO_DATE('2000-04-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (25, 'FAKHAR', 'ZAMAN', 'PAKISTAN', TO_DATE('1990-04-10', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (26, 'MOHAMMAD', 'RIZWAN', 'PAKISTAN', TO_DATE('1992-06-01', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (27, 'SHADAB', 'KHAN', 'PAKISTAN', TO_DATE('1998-10-04', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (28, 'IMAD', 'WASIM', 'PAKISTAN', TO_DATE('1988-12-18', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (29, 'HARIS', 'SOHAIL', 'PAKISTAN', TO_DATE('1989-01-09', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (30, 'SHOAIB', 'MALIK', 'PAKISTAN', TO_DATE('1982-02-01', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (31, 'WAHAB', 'RIAZ', 'PAKISTAN', TO_DATE('1985-06-28', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (32, 'USMAN', 'QADIR', 'PAKISTAN', TO_DATE('1993-08-05', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (33, 'IMRAN', 'KHAN', 'PAKISTAN', TO_DATE('1988-06-10', 'YYYY-MM-DD'), EMPTY_BLOB());
-- AUSTRALIA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (34, 'STEVE', 'SMITH', 'AUSTRALIA', TO_DATE('1989-06-02', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (35, 'DAVID', 'WARNER', 'AUSTRALIA', TO_DATE('1986-10-27', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (36, 'AARON', 'FINCH', 'AUSTRALIA', TO_DATE('1986-11-17', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (37, 'GLENN', 'MAXWELL', 'AUSTRALIA', TO_DATE('1988-10-14', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (38, 'MITCHELL', 'STARC', 'AUSTRALIA', TO_DATE('1990-01-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (39, 'PAT', 'CUMMINS', 'AUSTRALIA', TO_DATE('1993-05-08', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (40, 'ADAM', 'ZAMPA', 'AUSTRALIA', TO_DATE('1992-03-31', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (41, 'ALEX', 'CAREY', 'AUSTRALIA', TO_DATE('1991-08-27', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (42, 'MARCUS', 'STOINIS', 'AUSTRALIA', TO_DATE('1989-08-16', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (43, 'MATTHEW', 'WADE', 'AUSTRALIA', TO_DATE('1987-12-26', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (44, 'JOSH', 'HAZLEWOOD', 'AUSTRALIA', TO_DATE('1991-01-08', 'YYYY-MM-DD'), EMPTY_BLOB());
-- ENGLAND PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (45, 'JOE', 'ROOT', 'ENGLAND', TO_DATE('1990-12-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (46, 'EOIN', 'MORGAN', 'ENGLAND', TO_DATE('1986-09-10', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (47, 'JASON', 'ROY', 'ENGLAND', TO_DATE('1990-07-21', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (48, 'JOS', 'BUTTLER', 'ENGLAND', TO_DATE('1990-09-08', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (49, 'BEN', 'STOKES', 'ENGLAND', TO_DATE('1991-06-04', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (50, 'JOFRA', 'ARCHER', 'ENGLAND', TO_DATE('1995-04-03', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (51, 'MARK', 'WOOD', 'ENGLAND', TO_DATE('1990-01-11', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (52, 'ADIL', 'RASHID', 'ENGLAND', TO_DATE('1988-02-17', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (53, 'CHRIS', 'WOAKES', 'ENGLAND', TO_DATE('1989-03-02', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (54, 'TOM', 'CURRAN', 'ENGLAND', TO_DATE('1995-03-12', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (55, 'MOEEN', 'ALI', 'ENGLAND', TO_DATE('1987-06-18', 'YYYY-MM-DD'), EMPTY_BLOB());
-- NEW ZEALAND PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (56, 'KANE', 'WILLIAMSON', 'NEW ZEALAND', TO_DATE('1990-08-08', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (57, 'ROSS', 'TAYLOR', 'NEW ZEALAND', TO_DATE('1984-03-08', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (58, 'MARTIN', 'GUPTILL', 'NEW ZEALAND', TO_DATE('1986-09-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (59, 'TRENT', 'BOULT', 'NEW ZEALAND', TO_DATE('1989-07-22', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (60, 'LOCKIE', 'FERGUSON', 'NEW ZEALAND', TO_DATE('1991-06-13', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (61, 'COLIN', 'DE GRANDHOMME', 'NEW ZEALAND', TO_DATE('1986-07-22', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (62, 'TIM', 'SOUTHEE', 'NEW ZEALAND', TO_DATE('1988-12-11', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (63, 'KYLE', 'JAMIESON', 'NEW ZEALAND', TO_DATE('1994-12-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (64, 'JAMES', 'NEESHAM', 'NEW ZEALAND', TO_DATE('1990-09-17', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (65, 'TOM', 'LATHAM', 'NEW ZEALAND', TO_DATE('1992-04-02', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (66, 'MITCHELL', 'SANTNER', 'NEW ZEALAND', TO_DATE('1992-02-05', 'YYYY-MM-DD'), EMPTY_BLOB());
-- SOUTH AFRICA PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (67, 'QUINTON', 'DE KOCK', 'SOUTH AFRICA', TO_DATE('1992-12-17', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (68, 'FAF', 'DU PLESSIS', 'SOUTH AFRICA', TO_DATE('1984-07-13', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (69, 'DAVID', 'MILLER', 'SOUTH AFRICA', TO_DATE('1989-06-10', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (70, 'KAGISO', 'RABADA', 'SOUTH AFRICA', TO_DATE('1995-05-25', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (71, 'ANRICH', 'NORTJE', 'SOUTH AFRICA', TO_DATE('1993-11-16', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (72, 'LUNGI', 'NGIDI', 'SOUTH AFRICA', TO_DATE('1996-03-29', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (73, 'RASSIE', 'VAN DER DUSSEN', 'SOUTH AFRICA', TO_DATE('1989-06-07', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (74, 'ANDILE', 'PHEHLUKWAYO', 'SOUTH AFRICA', TO_DATE('1996-03-03', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (75, 'TEMBA', 'BAVUMA', 'SOUTH AFRICA', TO_DATE('1990-05-17', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (76, 'HEINRICH', 'KLAASEN', 'SOUTH AFRICA', TO_DATE('1991-07-30', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (77, 'AIDEN', 'MARKRAM', 'SOUTH AFRICA', TO_DATE('1994-10-04', 'YYYY-MM-DD'), EMPTY_BLOB());
-- AFGHANISTAN PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (78, 'RASHID', 'KHAN', 'AFGHANISTAN', TO_DATE('1998-09-20', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (79, 'MOHAMMAD', 'NABI', 'AFGHANISTAN', TO_DATE('1985-01-01', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (80, 'ASGHAR', 'AFGHAN', 'AFGHANISTAN', TO_DATE('1987-12-22', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (81, 'RAHMANULLAH', 'GURBAZ', 'AFGHANISTAN', TO_DATE('2001-09-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (82, 'HAZRATULLAH', 'ZAZAI', 'AFGHANISTAN', TO_DATE('1998-03-23', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (83, 'NAJIBULLAH', 'ZADRAN', 'AFGHANISTAN', TO_DATE('1993-02-01', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (84, 'MOHAMMAD', 'SHAHZAD', 'AFGHANISTAN', TO_DATE('1987-01-31', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (85, 'GULBADIN', 'NAIB', 'AFGHANISTAN', TO_DATE('1991-03-16', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (86, 'DAWLAT', 'ZADRAN', 'AFGHANISTAN', TO_DATE('1988-03-20', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (87, 'KARIM', 'JANAT', 'AFGHANISTAN', TO_DATE('1998-02-25', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (88, 'QAIS', 'AHMAD', 'AFGHANISTAN', TO_DATE('2000-12-05', 'YYYY-MM-DD'), EMPTY_BLOB());
-- WEST INDIES PLAYERS
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (89, 'CHRIS', 'GAYLE', 'WEST INDIES', TO_DATE('1979-09-21', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (90, 'ANDRE', 'RUSSELL', 'WEST INDIES', TO_DATE('1988-04-29', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (91, 'SHAI', 'HOPE', 'WEST INDIES', TO_DATE('1993-11-10', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (92, 'KIERON', 'POLLARD', 'WEST INDIES', TO_DATE('1987-05-12', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (93, 'EVIN', 'LEWIS', 'WEST INDIES', TO_DATE('1991-12-27', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (94, 'NICHOLAS', 'POORAN', 'WEST INDIES', TO_DATE('1995-10-02', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (95, 'SHELDON', 'COTTRELL', 'WEST INDIES', TO_DATE('1989-08-19', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (96, 'HAYDEN', 'WALSH', 'WEST INDIES', TO_DATE('1992-12-23', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (97, 'FABIAN', 'ALLEN', 'WEST INDIES', TO_DATE('1995-05-07', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (98, 'ROSTON', 'CHASE', 'WEST INDIES', TO_DATE('1992-03-22', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (99, 'ALZARRI', 'JOSEPH', 'WEST INDIES', TO_DATE('1996-11-20', 'YYYY-MM-DD'), EMPTY_BLOB());
-- UMPIRES
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (100, 'SIMON', 'TAUFEL', 'AUSTRALIA', TO_DATE('1971-01-21', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (101, 'ALEEM', 'DAR', 'PAKISTAN', TO_DATE('1968-06-06', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (102, 'KUMAR', 'DHARMASENA', 'SRI LANKA', TO_DATE('1971-04-24', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (103, 'RICHARD', 'KETTLEBOROUGH', 'ENGLAND', TO_DATE('1973-03-15', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (104, 'BRUCE', 'OXENFORD', 'AUSTRALIA', TO_DATE('1960-03-5', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (105, 'MARAIS', 'ERASMUS', 'SOUTH AFRICA', TO_DATE('1964-02-3', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (106, 'PAUL', 'REIFFEL', 'AUSTRALIA', TO_DATE('1966-01-12', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (107, 'JOEL', 'WILSON', 'WEST INDIES', TO_DATE('1966-03-15', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (108, 'NITIN', 'MENON', 'INDIA', TO_DATE('1974-10-31', 'YYYY-MM-DD'), EMPTY_BLOB());

INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (109, 'CHRIS', 'GAFFANEY', 'NEW ZEALAND', TO_DATE('1975-02-10', 'YYYY-MM-DD'), EMPTY_BLOB());
-- BANGLADESH COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (110, 'RUSSELL', 'DOMINGO', 'SOUTH AFRICA', TO_DATE('1974-08-30', 'YYYY-MM-DD'), EMPTY_BLOB());

-- INDIA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (111, 'RAVI', 'SHASTRI', 'INDIA', TO_DATE('1962-05-27', 'YYYY-MM-DD'), EMPTY_BLOB());

-- PAKISTAN COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (112, 'MATTHEW', 'HAYDEN', 'AUSTRALIA', TO_DATE('1971-10-29', 'YYYY-MM-DD'), EMPTY_BLOB());

-- AUSTRALIA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (113, 'JUSTIN', 'LANGER', 'AUSTRALIA', TO_DATE('1970-11-21', 'YYYY-MM-DD'), EMPTY_BLOB());

-- ENGLAND COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (114, 'CHRIS', 'SILVERWOOD', 'ENGLAND', TO_DATE('1975-03-05', 'YYYY-MM-DD'), EMPTY_BLOB());

-- NEW ZEALAND COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (115, 'GARY', 'STEAD', 'NEW ZEALAND', TO_DATE('1972-08-23', 'YYYY-MM-DD'), EMPTY_BLOB());

-- SOUTH AFRICA COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (116, 'MARK', 'BOUCHER', 'SOUTH AFRICA', TO_DATE('1976-12-03', 'YYYY-MM-DD'), EMPTY_BLOB());

-- AFGHANISTAN COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (117, 'LANCE', 'KLUSENER', 'SOUTH AFRICA', TO_DATE('1971-09-04', 'YYYY-MM-DD'), EMPTY_BLOB());

-- WEST INDIES COACH
INSERT INTO PERSON (PERSONID, FIRST_NAME, LAST_NAME, NATIONALITY, DATE_OF_BIRTH, IMAGE)
VALUES (118, 'PHIL', 'SIMMONS', 'WEST INDIES', TO_DATE('1963-04-18', 'YYYY-MM-DD'), EMPTY_BLOB());
