-- BANGLADESH PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71101, 71, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71102, 71, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71103, 71, 'WICKETKEEPER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71104, 71, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71105, 71, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71106, 71, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71107, 71, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71108, 71, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71109, 71, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71110, 71, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (71111, 71, 'BOWLER');

-- INDIA PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72101, 72, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72102, 72, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72103, 72, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72104, 72, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72105, 72, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72106, 72, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72107, 72, 'WICKETKEEPER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72108, 72, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72109, 72, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72110, 72, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (72111, 72, 'BOWLER');

-- PAKISTAN PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73101, 73, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73102, 73, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73103, 73, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73104, 73, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73105, 73, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73106, 73, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73107, 73, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73108, 73, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73109, 73, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73110, 73, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (73111, 73, 'BOWLER');

-- AUSTRALIA PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74101, 74, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74102, 74, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74103, 74, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74104, 74, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74105, 74, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74106, 74, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74107, 74, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74108, 74, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74109, 74, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74110, 74, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (74111, 74, 'BOWLER');

-- ENGLAND PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75101, 75, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75102, 75, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75103, 75, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75104, 75, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75105, 75, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75106, 75, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75107, 75, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75108, 75, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75109, 75, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75110, 75, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (75111, 75, 'BOWLER');

-- NEW ZEALAND PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76101, 76, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76102, 76, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76103, 76, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76104, 76, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76105, 76, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76106, 76, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76107, 76, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76108, 76, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76109, 76, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76110, 76, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (76111, 76, 'BOWLER');

-- SOUTH AFRICA PLAYERS
INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77101, 77, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77102, 77, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77103, 77, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77104, 77, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77105, 77, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77106, 77, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77107, 77, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77108, 77, 'BATSMAN');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77109, 77, 'BOWLER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77110, 77, 'ALL-ROUNDER');

INSERT INTO PLAYER (PLAYERID, TEAM_ID, TYPE)
VALUES (77111, 77, 'BOWLER');

-- AFGHANISTAN PLAYERS
INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BOWLER', 78101);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'ALL-ROUNDER', 78102);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BATSMAN', 78103);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BATSMAN', 78104);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BATSMAN', 78105);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'ALL-ROUNDER', 78106);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'WICKET-KEEPER', 78107);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'ALL-ROUNDER', 78108);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BOWLER', 78109);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BOWLER', 78110);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (78, 'BOWLER', 78111);

-- WEST INDIES PLAYERS
INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BATSMAN', 79101);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'ALL-ROUNDER', 79102);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BATSMAN', 79103);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'ALL-ROUNDER', 79104);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BATSMAN', 79105);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'WICKET-KEEPER', 79106);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BOWLER', 79107);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BOWLER', 79108);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BOWLER', 79109);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'ALL-ROUNDER', 79110);

INSERT INTO PLAYER (TEAM_ID, TYPE, PLAYERID)
VALUES (79, 'BOWLER', 79111);
