INSERT INTO PLAYER_PROFILE (PLAYERID, MATCH_TYPE,MATCH_PLAYED, RUNS, HIGHEST_SCORE, AVERAGE, STRIKE_RATE, HUNDREDS, FIFTIES, FOURS, SIXES, WICKETS, MAIDEN_OVERS, ECONOMY_RATE, BEST_BOWLING_WICKET,BEST_BOWLING_RUN, BOWLING_AVERAGE, FIVE_WICKETS, TEN_WICKETS, HATRICKS) 
SELECT 
    PLAYERID, 
    'ODI' AS MATCH_TYPE,
    FLOOR(200+RANDOM() * 250) AS MATCH_PLAYED,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(5000 + RANDOM() * 10000)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(3000 + RANDOM() * 8000)
        ELSE FLOOR(1000 + RANDOM() * 2000) 
    END AS RUNS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(50 + RANDOM() * 200)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 200)
        ELSE FLOOR(10 + RANDOM() * 45) 
    END AS HIGHEST_SCORE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(35 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(35 + RANDOM() * 20)
        ELSE FLOOR(10 + RANDOM() * 15) 
    END AS AVERAGE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(70 + RANDOM() * 80)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(70 + RANDOM() * 80)
        ELSE FLOOR(10 + RANDOM() * 30) 
    END AS STRIKE_RATE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(10 + RANDOM() * 50)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 50)
        ELSE FLOOR(RANDOM() *3) 
    END AS HUNDREDS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(10 + RANDOM() * 80)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 80)
        ELSE FLOOR(RANDOM() * 5) 
    END AS FIFTIES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(100 + RANDOM() * 250)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(100 + RANDOM() * 250)
        ELSE FLOOR (RANDOM() * 20) 
    END AS SIXES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(150 + RANDOM() * 450)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(150 + RANDOM() * 450)
        ELSE FLOOR (RANDOM() * 50) 
    END AS FOURS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(50 + RANDOM() * 100)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 100)
        ELSE NULL 
    END AS WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20 + RANDOM() * 20)
        ELSE NULL 
    END AS MAIDEN_OVERS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(3 + RANDOM() * 7.5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(3 + RANDOM() * 7.5)
        ELSE NULL 
    END AS ECONOMY_RATE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(RANDOM() * 5)
        ELSE NULL 
    END AS BEST_BOWLING_WICKET,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20+RANDOM() * 25)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20+RANDOM() * 25)
        ELSE NULL 
    END AS BEST_BOWLING_RUN,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(15 + RANDOM() * 30)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(15 + RANDOM() * 30)
        ELSE NULL 
    END AS BOWLING_AVERAGE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 15)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 15)
        ELSE NULL 
    END AS FIVE_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(2 + RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(2 + RANDOM() * 5)
        ELSE NULL 
    END AS TEN_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 20)
        ELSE NULL 
    END AS HATRICKS
FROM 
    PLAYER;
	
	
	
-- FOR TEST MATCH
INSERT INTO PLAYER_PROFILE (PLAYERID, MATCH_TYPE,MATCH_PLAYED, RUNS, HIGHEST_SCORE, AVERAGE, STRIKE_RATE, HUNDREDS, FIFTIES, FOURS, SIXES, WICKETS, MAIDEN_OVERS, ECONOMY_RATE, BEST_BOWLING_WICKET,BEST_BOWLING_RUN, BOWLING_AVERAGE, FIVE_WICKETS, TEN_WICKETS, HATRICKS) 
SELECT 
    PLAYERID, 
    'TEST' AS MATCH_TYPE,
    FLOOR(100+RANDOM() * 150) AS MATCH_PLAYED,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(2000 + RANDOM() * 5000)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(2000 + RANDOM() * 5000)
        ELSE FLOOR(500 + RANDOM() * 200) 
    END AS RUNS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(50 + RANDOM() * 200)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 200)
        ELSE FLOOR(10 + RANDOM() * 45) 
    END AS HIGHEST_SCORE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(25 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(25 + RANDOM() * 20)
        ELSE FLOOR(10 + RANDOM() * 10) 
    END AS AVERAGE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(80 + RANDOM() *80)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(80 + RANDOM() * 80)
        ELSE FLOOR(40 + RANDOM() * 50) 
    END AS STRIKE_RATE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(RANDOM() *5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(RANDOM() * 5)
        ELSE FLOOR(RANDOM() *1) 
    END AS HUNDREDS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(RANDOM() *40)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR( RANDOM() * 40)
        ELSE FLOOR(RANDOM()*2) 
    END AS FIFTIES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(100 + RANDOM() * 250)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(100 + RANDOM() * 250)
        ELSE FLOOR (RANDOM() * 20) 
    END AS SIXES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(150 + RANDOM() * 450)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(150 + RANDOM() * 450)
        ELSE FLOOR (RANDOM() * 50) 
    END AS FOURS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(50 + RANDOM() * 100)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 100)
        ELSE NULL 
    END AS WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20 + RANDOM() * 20)
        ELSE NULL 
    END AS MAIDEN_OVERS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(4.5 + RANDOM() * 9.5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(4.5 + RANDOM() * 9.5)
        ELSE NULL 
    END AS ECONOMY_RATE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(RANDOM() * 5)
        ELSE NULL 
    END AS BEST_BOWLING_WICKET,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20+RANDOM() * 25)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20+RANDOM() * 25)
        ELSE NULL 
    END AS BEST_BOWLING_RUN,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(15 + RANDOM() * 30)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(15 + RANDOM() * 30)
        ELSE NULL 
    END AS BOWLING_AVERAGE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 15)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 15)
        ELSE NULL 
    END AS FIVE_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(2 + RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(2 + RANDOM() * 5)
        ELSE NULL 
    END AS TEN_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 20)
        ELSE NULL 
    END AS HATRICKS
FROM 
    PLAYER;
	
	
-- FOR T20 MATCH
INSERT INTO PLAYER_PROFILE (PLAYERID, MATCH_TYPE,MATCH_PLAYED, RUNS, HIGHEST_SCORE, AVERAGE, STRIKE_RATE, HUNDREDS, FIFTIES, FOURS, SIXES, WICKETS, MAIDEN_OVERS, ECONOMY_RATE, BEST_BOWLING_WICKET,BEST_BOWLING_RUN, BOWLING_AVERAGE, FIVE_WICKETS, TEN_WICKETS, HATRICKS) 
SELECT 
    PLAYERID, 
    'TTWENTY' AS MATCH_TYPE,
    FLOOR(100+RANDOM() * 150) AS MATCH_PLAYED,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(2000 + RANDOM() * 5000)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(2000 + RANDOM() * 5000)
        ELSE FLOOR(500 + RANDOM() * 200) 
    END AS RUNS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(50 + RANDOM() * 200)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 200)
        ELSE FLOOR(10 + RANDOM() * 45) 
    END AS HIGHEST_SCORE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(25 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(25 + RANDOM() * 20)
        ELSE FLOOR(10 + RANDOM() * 10) 
    END AS AVERAGE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(80 + RANDOM() *80)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(80 + RANDOM() * 80)
        ELSE FLOOR(40 + RANDOM() * 50) 
    END AS STRIKE_RATE,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(RANDOM() *5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(RANDOM() * 5)
        ELSE FLOOR(RANDOM() *1) 
    END AS HUNDREDS,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(RANDOM() *40)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR( RANDOM() * 40)
        ELSE FLOOR(RANDOM()*2) 
    END AS FIFTIES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(100 + RANDOM() * 250)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(100 + RANDOM() * 250)
        ELSE FLOOR (RANDOM() * 20) 
    END AS SIXES,
    CASE 
        WHEN TYPE = 'BATSMAN' THEN FLOOR(150 + RANDOM() * 450)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(150 + RANDOM() * 450)
        ELSE FLOOR (RANDOM() * 50) 
    END AS FOURS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(50 + RANDOM() * 100)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(50 + RANDOM() * 100)
        ELSE NULL 
    END AS WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20 + RANDOM() * 20)
        ELSE NULL 
    END AS MAIDEN_OVERS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(4.5 + RANDOM() * 9.5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(4.5 + RANDOM() * 9.5)
        ELSE NULL 
    END AS ECONOMY_RATE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(RANDOM() * 5)
        ELSE NULL 
    END AS BEST_BOWLING_WICKET,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(20+RANDOM() * 25)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(20+RANDOM() * 25)
        ELSE NULL 
    END AS BEST_BOWLING_RUN,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(15 + RANDOM() * 30)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(15 + RANDOM() * 30)
        ELSE NULL 
    END AS BOWLING_AVERAGE,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 15)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 15)
        ELSE NULL 
    END AS FIVE_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(2 + RANDOM() * 5)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(2 + RANDOM() * 5)
        ELSE NULL 
    END AS TEN_WICKETS,
    CASE 
        WHEN TYPE = 'BOWLER' THEN FLOOR(10 + RANDOM() * 20)
        WHEN TYPE ='ALL-ROUNDER' THEN FLOOR(10 + RANDOM() * 20)
        ELSE NULL 
    END AS HATRICKS
FROM 
    PLAYER;
	

















