INSERT INTO TEAM_PARTICIPATION (TEAM_ID, TOURNAMENT_ID) VALUES (71, 4);
INSERT INTO TEAM_PARTICIPATION (TEAM_ID, TOURNAMENT_ID) VALUES (72, 4);
INSERT INTO TEAM_PARTICIPATION (TEAM_ID, TOURNAMENT_ID) VALUES (80, 4);