-- INSERTING DATA INTO THE TEAM TABLE
INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (1, 'BANGLADESH', 'RUSSELL DOMINGO', 'SHAKIB AL HASAN');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (2, 'INDIA', 'RAVI SHASTRI', 'ROHIT SHARMA');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (3, 'PAKISTAN', 'MATTHEW HAYDEN', 'BABAR AZAM');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (4, 'AUSTRALIA', 'JUSTIN LANGER', 'PAT CUMMINS');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (5, 'ENGLAND', 'CHRIS SILVERWOOD', 'JOS BUTTLER');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (6, 'NEW ZEALAND', 'GARY STEAD', 'KANE WILLIAMSON');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (7, 'SOUTH AFRICA', 'MARK BOUCHER', 'TEMBA BAVUMA');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (8, 'AFGHANISTAN', 'LANCE KLUSENER', 'HASHMATULLAH SHAHIDI');

INSERT INTO TEAM (TEAM_ID, TEAM_NAME, COACH_NAME, CAPTAIN_NAME)
VALUES (9, 'WEST INDIES', 'PHIL SIMMONS', 'JASON HOLDER');
