-- INSERT DATA INTO UMPIRE TABLE WITH NO_OF_MATCH_CONDUCTED SET TO 0
INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (100, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (101, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (102, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (103, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (104, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (105, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (106, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (107, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (108, 0);

INSERT INTO UMPIRE (PERSONID, NO_OF_MATCH_CONDUCTED)
VALUES (109, 0);